sync

diff --git a/.github/workflows/backport-command.yml b/.github/workflows/backport-command.yml
--- a/.github/workflows/backport-command.yml
+++ b/.github/workflows/backport-command.yml
@@ -7,7 +7,6 @@ jobs:
   # outputs the source of the comment (PR or issue)
   backport-type:
     outputs:
-      type: ${{ steps.type.outputs.type }}
       commented_on: ${{ steps.type.outputs.commented_on }}
     runs-on: ubuntu-latest
     env:
@@ -21,42 +20,23 @@ jobs:
           CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
         id: type
         run: |
+          branches=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/branches" --jq '.[] | select(.name=='\"$ARG1\"')')
+          if [[ $branches == "" ]]; then
+            echo "Branch name not found"
+            exit 1
+          fi
           if [[ $(echo $CLIENT_PAYLOAD | jq 'has("pull_request")') == true ]]; then
             commented_on=pr
           else
             commented_on=issue
           fi
           echo "::set-output name=commented_on::$commented_on"
-          branches=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/branches" --jq '.[] | select(.name=='\"$ARG1\"')')
-          if [[ $branches == "" ]]; then
-            # not a branch; checking if its a PR
-            pulls=$(gh api "repos/${TARGET_ORG}/${TARGET_REPO}/pulls/$ARG1" --jq '. | select(.state=="closed")')
-            if [[ $pulls == "" ]]; then
-              echo "The provided argument is neither branch nor a pr"
-              exit 2
-            else
-              # case valid PR number
-              if [[ "$commented_on" == "pr" ]]; then
-                echo "Provided PR number in PR comment. You should use PR numbers only on issue somments"
-                exit 2
-              else
-                echo "::set-output name=type::pr"
-              fi
-            fi
-          else
-            # case valid branch name
-            # this case applies for both creating issue and PRs
-            # thus it is accepted in any case
-            echo "::set-output name=type::branch"
-          fi
 
   # creates backport issue if commented on issue, or
   # creates backport PR if commented on PR
   # eg /backport v21.11.x
-  # TODO: add functionality to create PRs when commenting on issues
   type-branch:
     needs: backport-type
-    if: needs.backport-type.outputs.type == 'branch'
     runs-on: ubuntu-latest
     env:
       TARGET_ORG: ${{ github.event.client_payload.slash_command.args.named.org }}
@@ -109,13 +89,35 @@ jobs:
           BACKPORT_BRANCH: ${{ steps.branch.outputs.branch }}
           ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
           ORIG_ASSIGNEES: ${{ steps.assignees.outputs.assignees }}
-          ORIG_COMMENT_URL: ${{ github.event.client_payload.github.payload.comment.html_url }}
+          ORIG_ISSUE_URL: ${{ github.event.client_payload.github.payload.issue.html_url }}
         run: |
-          gh issue create --title "[${BACKPORT_BRANCH}] ${ORIG_TITLE}" \
-            --repo "${TARGET_ORG}/${TARGET_REPO}" \
-            --assignee "${ORIG_ASSIGNEES}" \
-            --milestone "${TARGET_MILESTONE}" \
-            --body "Backport ${ORIG_COMMENT_URL} to branch ${BACKPORT_BRANCH}"
+          label_exists=$(gh label list --repo "$TARGET_ORG/$TARGET_REPO" --limit 500 | grep "kind/backport")
+          if [[ "$label_exists" == "" ]]; then
+            gh label create "kind/backport" --repo "$TARGET_ORG/$TARGET_REPO"
+          fi
+          backport_issue_url=$(gh issue list --repo "${TARGET_ORG}/${TARGET_REPO}" \
+              --state open \
+              --search "[${BACKPORT_BRANCH}] ${ORIG_TITLE} in:title" \
+              --json url \
+              --milestone "${TARGET_MILESTONE}" \
+              --jq '.[0].url')
+          if [[ "$backport_issue_url" == "" ]]; then
+            gh issue create --title "[${BACKPORT_BRANCH}] ${ORIG_TITLE}" \
+              --label "kind/backport" \
+              --repo "${TARGET_ORG}/${TARGET_REPO}" \
+              --assignee "${ORIG_ASSIGNEES}" \
+              --milestone "${TARGET_MILESTONE}" \
+              --body "Backport ${ORIG_ISSUE_URL} to branch ${BACKPORT_BRANCH}"
+          else
+            gh issue comment "$ORIG_ISSUE_URL" --body "Backport issue already exists: $backport_issue_url"
+          fi
+
+      - name: Get reviewers of PR
+        if: needs.backport-type.outputs.commented_on == 'pr'
+        env:
+          REVIEWERS: ${{ toJson(github.event.client_payload.pull_request.requested_reviewers) }}
+        id: reviewers
+        run: echo ::set-output name=reviewers::$(echo "$REVIEWERS" | jq -r '.[].login' | paste -s -d ',' -)
 
       - name: Get commits of PR
         if: needs.backport-type.outputs.commented_on == 'pr'
@@ -130,7 +132,47 @@ jobs:
       - uses: actions/checkout@v3
         if: needs.backport-type.outputs.commented_on == 'pr'
         with:
-          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
+          repository: vbotbuildovich/redpanda
+          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
+
+      - name: Backport commits
+        if: needs.backport-type.outputs.commented_on == 'pr'
+        env:
+          PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
+          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
+          BACKPORT_BRANCH: ${{ steps.branch.outputs.branch }}
+          ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
+          BACKPORT_COMMITS: ${{ steps.backport_commits.outputs.backport_commits }}
+          IS_MERGED: ${{ github.event.client_payload.pull_request.merged }}
+        id: pr_details
+        run: |
+          if [[ "$IS_MERGED" != true ]]; then
+            msg="The pull request is not merged yet. Cancelling..."
+            echo "$msg"
+            gh pr comment "$PR_NUMBER" \
+              --body "$msg" \
+              --repo "$TARGET_ORG/$TARGET_REPO"
+            exit 1
+          fi
+          fixing_issue_url=$(gh pr view "$PR_NUMBER" --repo "$TARGET_ORG/$TARGET_REPO" --json body --jq .body \
+            | grep 'close\|fix\|resolve' \
+            | grep ' https://github.com/\|:https://github.com/\|: https://github.com' \
+            | grep -Eo '(http.*)' | head -1 \
+            || "")
+          # ensure unique branch
+          suffix=$(echo $(($RANDOM % 1000)))
+          git config --global user.email "vbot@vectorized.io"
+          git config --global user.name "vbotbuildovich"
+          git remote add upstream "https://github.com/$TARGET_ORG/$TARGET_REPO.git"
+          git fetch --all
+          git remote set-url origin "https://vbotbuildovich:$GITHUB_TOKEN@github.com/vbotbuildovich/$TARGET_REPO.git"
+          head_branch=$(echo "backport-$ORIG_TITLE-to-$BACKPORT_BRANCH-$suffix" | sed 's/ /-/g' | tr -d '[]')
+          git checkout -b $head_branch remotes/upstream/$BACKPORT_BRANCH
+          git cherry-pick -x $BACKPORT_COMMITS
+          git push --set-upstream origin $head_branch
+          git remote rm upstream
+          echo ::set-output name=head_branch::$head_branch
+          echo ::set-output name=fixing_issue_url::$fixing_issue_url
 
       - name: Create pull request
         if: needs.backport-type.outputs.commented_on == 'pr'
@@ -139,134 +181,59 @@ jobs:
           TARGET_MILESTONE: ${{ steps.milestone.outputs.milestone }}
           BACKPORT_BRANCH: ${{ steps.branch.outputs.branch }}
           ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
-          ORIG_ASSIGNEES: ${{ steps.assignees.outputs.assignees }}
-          ORIG_COMMENT_URL: ${{ github.event.client_payload.github.payload.comment.html_url }}
-          IS_MERGED: ${{ github.event.client_payload.pull_request.merged }}
-          BACKPORT_COMMITS: ${{ steps.backport_commits.outputs.backport_commits }}
+          ORIG_REVIEWERS: ${{ steps.reviewers.outputs.reviewers }}
+          ORIG_ISSUE_URL: ${{ github.event.client_payload.github.payload.issue.html_url }}
+          HEAD_BRANCH: ${{ steps.pr_details.outputs.head_branch }}
+          FIXING_ISSUE_URL: ${{ steps.pr_details.outputs.fixing_issue_url }}
+          ORIG_PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
         run: |
-          if [[ "$IS_MERGED" != true ]]; then
-            echo "The pull request is not merged yet. Cancelling..."
-            exit 1
+          label_exists=$(gh label list --repo "$TARGET_ORG/$TARGET_REPO" --limit 500 | grep "kind/backport")
+          if [[ "$label_exists" == "" ]]; then
+            gh label create "kind/backport" --repo "$TARGET_ORG/$TARGET_REPO"
           fi
-          # ensure unique branch
-          suffix=$(echo $(($RANDOM % 1000)))
-          git fetch
-          git remote -vv
-          git config --global user.email "vbot@vectorized.io"
-          git config --global user.name "vbotbuildovich"
-          branch_name=$(echo "backport-$ORIG_TITLE-to-$BACKPORT_BRANCH-$suffix" | sed 's/ /-/g')
-          issue_number=$(gh issue list --repo "${TARGET_ORG}/${TARGET_REPO}" \
-            --state open \
-            --search "[${BACKPORT_BRANCH}] ${ORIG_TITLE} in:title" \
-            --json number \
-            --milestone "${TARGET_MILESTONE}" \
-            --jq '.[0].number')
-          git checkout -b $branch_name remotes/origin/$BACKPORT_BRANCH
-          git cherry-pick -x $BACKPORT_COMMITS
-          git push --set-upstream origin $branch_name
+          if [[ "$FIXING_ISSUE_URL" != "" ]]; then
+            orig_issue_number=$(echo "$FIXING_ISSUE_URL" | awk -F/ '{print $NF}')
+            orig_issue_title=$(gh issue view "$orig_issue_number" \
+              --repo "${TARGET_ORG}/${TARGET_REPO}" \
+              --json title --jq .title)
+
+            backport_issue_url=$(gh issue list --repo "${TARGET_ORG}/${TARGET_REPO}" \
+              --state open \
+              --search "[${BACKPORT_BRANCH}] ${orig_issue_title} in:title" \
+              --json url \
+              --milestone "${TARGET_MILESTONE}" \
+              --jq '.[0].url')
+
+            if [[ "$backport_issue_url" == "" ]]; then
+              # backport issue does not exist and will be created
+              # get orig issue assignees
+              orig_issue_assingees=$(gh issue view "$orig_issue_number" \
+                --repo "${TARGET_ORG}/${TARGET_REPO}" \
+                --json assignees --jq .assignees.[].login | paste -s -d ',' -)
+              # create issue
+              backport_issue_url=$(gh issue create --title "[${BACKPORT_BRANCH}] ${orig_issue_title}" \
+                --label "kind/backport" \
+                --repo "${TARGET_ORG}/${TARGET_REPO}" \
+                --assignee "${orig_issue_assingees}" \
+                --milestone "${TARGET_MILESTONE}" \
+                --body "Backport ${FIXING_ISSUE_URL} to branch ${BACKPORT_BRANCH}")
+              # post a comment on original PR
+              gh pr comment "$ORIG_PR_NUMBER" \
+                --body "Created backport issue $backport_issue_url" \
+                --repo "$TARGET_ORG/$TARGET_REPO"
+            fi
+          fi
+
           gh pr create --title "[${BACKPORT_BRANCH}] ${ORIG_TITLE}" \
             --base "${BACKPORT_BRANCH}" \
+            --label "kind/backport" \
+            --head "vbotbuildovich:${HEAD_BRANCH}" \
             --draft \
             --repo "${TARGET_ORG}/${TARGET_REPO}" \
-            --assignee "${ORIG_ASSIGNEES}" \
+            --reviewer "${ORIG_REVIEWERS}" \
             --milestone "${TARGET_MILESTONE}" \
-            --body """Backport from pull request: ${ORIG_COMMENT_URL}
-            Fixes $issue_number
-            """
-
-      - name: Add reaction
-        uses: peter-evans/create-or-update-comment@v1
-        with:
-          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
-          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
-          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
-          reaction-type: hooray
-
-  # works ONLY on backport issue comments. creates the backport PR
-  # eg /backport 123
-  type-pr:
-    needs: backport-type
-    if: needs.backport-type.outputs.type == 'pr'
-    runs-on: ubuntu-latest
-    env:
-      TARGET_ORG: ${{ github.event.client_payload.slash_command.args.named.org }}
-      TARGET_REPO: ${{ github.event.client_payload.slash_command.args.named.repo }}
-    steps:
-      - name: Get assignees
-        env:
-          ASSIGNEES: ${{ toJson(github.event.client_payload.github.payload.issue.assignees) }}
-        id: assignees
-        run: echo ::set-output name=assignees::$(echo "$ASSIGNEES" | jq -r '.[].login' | paste -s -d ',' -)
-
-      - name: Discover branch
-        env:
-          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
-          ISSUE_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
-        id: branch
-        run: |
-          backport_branch=$(echo $ISSUE_TITLE | grep -Eo '^(\[.*\])' | tr -d '[]')
-          branches=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/branches" --jq .[].name | grep "$backport_branch")
-          if [[ $branches == "" ]]; then
-            exit 2
-          fi
-          echo ::set-output name=branch::"$backport_branch"
-
-      - name: Discover milestone
-        env:
-          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
-          BACKPORT_BRANCH: ${{ steps.branch.outputs.branch }}
-          ISSUE_NUMBER: ${{ github.event.client_payload.github.payload.issue.number }}
-        id: milestone
-        run: |
-          milestone=$(gh api "/repos/${TARGET_ORG}/${TARGET_REPO}/issues/$ISSUE_NUMBER" --jq .milestone.title)
-          if [[ $milestone == "" ]]; then
-            echo "No milestone found on the issue"
-            exit 2
-          fi
-          echo ::set-output name=milestone::$milestone
-
-      - name: Get commits of PR
-        env:
-          BACKPORT_PR_NUMBER: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
-          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
-        id: backport_commits
-        run: |
-          backport_commits=$(gh api "repos/$TARGET_ORG/$TARGET_REPO/pulls/$BACKPORT_PR_NUMBER/commits" --jq .[].sha | paste -s -d ' ' -)
-          echo ::set-output name=backport_commits::$backport_commits
-
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
-
-      - name: Create pull request
-        env:
-          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
-          TARGET_MILESTONE: ${{ steps.milestone.outputs.milestone }}
-          BACKPORT_BRANCH: ${{ steps.branch.outputs.branch }}
-          ORIG_TITLE: ${{ github.event.client_payload.github.payload.issue.title }}
-          ORIG_ASSIGNEES: ${{ steps.assignees.outputs.assignees }}
-          ORIG_COMMENT_URL: ${{ github.event.client_payload.github.payload.comment.html_url }}
-          BACKPORT_COMMITS: ${{ steps.backport_commits.outputs.backport_commits }}
-          ORIG_ISSUE_URL: ${{ github.event.client_payload.github.payload.issue.html_url }}
-        run: |
-          # ensure unique branch
-          suffix=$(echo $(($RANDOM % 1000)))
-          git fetch
-          git remote -vv
-          git config --global user.email "vbot@vectorized.io"
-          git config --global user.name "vbotbuildovich"
-          branch_name=$(echo "backport-$ORIG_TITLE-to-$BACKPORT_BRANCH-$suffix" | sed 's/ /-/g' | tr -d '[]')
-          git checkout -b $branch_name remotes/origin/$BACKPORT_BRANCH
-          git cherry-pick -x $BACKPORT_COMMITS
-          git push --set-upstream origin $branch_name
-          gh pr create --title "${ORIG_TITLE}" \
-            --base "${BACKPORT_BRANCH}" \
-            --draft \
-            --repo "${TARGET_ORG}/${TARGET_REPO}" \
-            --assignee "${ORIG_ASSIGNEES}" \
-            --milestone "${TARGET_MILESTONE}" \
-            --body """Backport from pull request: ${ORIG_COMMENT_URL}
-            Fixes $ORIG_ISSUE_URL
+            --body """Backport from pull request: ${ORIG_ISSUE_URL}
+            Fixes $backport_issue_url
             """
 
       - name: Add reaction
